namespace MirClient.Core.World;

public readonly record struct ActorMarker(
    int X,
    int Y,
    int FromX,
    int FromY,
    byte Dir,
    int Feature,
    int Status,
    ushort Action,
    long ActionStartTimestamp,
    bool IsMyself,
    bool ItemExplore = false,
    string UserName = "",
    string DescUserName = "",
    float NameOffset = 0f,
    byte NameColor = 255,
    byte Attribute = 0,
    long LastQueryUserNameMs = 0,
    int Hp = 0,
    int MaxHp = 0,
    int LastDamage = 0,
    long LastDamageTimestampMs = 0,
    int FeatureEx = 0,
    int HitSpeed = 0,
    int TitleIndex = 0,
    int ChrLight = 0,
    bool OpenHealth = false,
    bool InstanceOpenHealth = false,
    long OpenHealthStartMs = 0,
    int OpenHealthDurationMs = 0,
    int IPower = 0,
    bool WeaponEffect = false,
    long WeaponEffectStartMs = 0,
    int MagicServerCode = 0,
    int MagicSerial = 0,
    int MagicEffectNumber = 0,
    int MagicEffectType = 0,
    int MagicTarget = 0,
    int MagicTargetX = 0,
    int MagicTargetY = 0,
    int MagicSpellLevel = 0,
    int MagicPoison = 0,
    int MagicFireLevel = 0,
    long MagicWaitStartMs = 0,
    long MagicAnimStartMs = 0,
    bool MagicHold = false);
